version: '3'
services:
  valorant-meister:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
    environment:
      - TZ=Asia/Tokyo
      - BOT_USERNAME=valorant-meister
      - BOT_TOKEN=YOUR_TOKEN
      - BOT_OWNER_ID=OWNER_ID
      - BOT_COMMAND_PREFIX=!valorant
      - AUTHORIZED_ROLES=Admin,Mod
      - TYPEORM_DATABASE=db/db.sqlite3
